app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from . import login_manager
from flask_login import UserMixin
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__='users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    password_hash = db.Column(db.String(255))
    pass_secure = db.Column(db.String(255))
    blogs = db.relationship('Blog',backref = 'user',lazy = "dynamic")
    comment = db.relationship('Comment',backref = 'user',lazy = "dynamic")

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return f'User {self.username}'

class Blog(db.Model):
    __tablename__='blogs'
    id = db.Column(db.Integer,primary_key=True)
    title = db.Column(db.String(255)) 
    category = db.Column(db.String(255)) 
    blog = db.Column(db.String(1000000))
    date = db.Column(db.DateTime(250), default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    comments = db.relationship('Comment', backref='blog', lazy='dynamic')

    def save_blog(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    def __repr__(self):
        return f"Pitches {self.blog}','{self.date}')" 

class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer, primary_key=True)
    comment = db.Column(db.String(255))
    date_posted = db.Column(db.DateTime(250), default=datetime.utcnow)
    blogs_id = db.Column(db.Integer, db.ForeignKey("blogs.id"))
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

class Subscriber(db.Model):
    __tablename__='subscribers'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)

    def __repr__(self):
        return f'Subscriber {self.username}'

class Quote:
    '''
    Source class to define News Source Objects
    '''
    def __init__(self,id,author,quote):
        self.id = id
        self.author = author
        self.quote = quote

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import Required
from wtforms.validators import Email
from ..models import Subscriber
from wtforms import ValidationError


class BlogForm(FlaskForm):

    title = StringField('Blog title',validators=[Required()])
    blog = TextAreaField('Add a Blog', validators=[Required()]) 
    category = SelectField('Choose Blog Category', choices = [('Travel','Travel'),('Music','Music'),('Photography','Photography'),('Food','Food')],validators=[Required()])
    submit = SubmitField('Add')

class CommentForm(FlaskForm):

    comment = TextAreaField('Add a comment', validators=[Required()])
    submit = SubmitField('Submit')

class UpdateForm(FlaskForm):
    email = StringField('Your Email Address',validators=[Required(),Email()])
    username = StringField('Enter your username',validators = [Required()])
    submit = SubmitField('Submit')

    def validate_email(self,data_field):
        if Subscriber.query.filter_by(email = data_field.data).first():
            raise ValidationError('You are already subscribed')

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
bootstrap = Bootstrap()
db = SQLAlchemy()
mail = Mail()

def create_app(config_name):

    app = Flask(__name__)

    app.config.from_object(config_options[config_name])

    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    
    from .request import configure_request
    configure_request(app)

    return app

from .main import views

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views

app/main/views.py
from flask import render_template,redirect,url_for,abort,request
from . import main
from flask_login import login_required,current_user
from .forms import BlogForm,CommentForm,UpdateForm
from ..models import User,Blog,Comment,Subscriber
from ..request import get_quotes
from .. import db
from ..email import mail_message

# Views
@main.route('/')
def index():

    '''
    View root page function that returns the index page and its data
    '''
    blogs = Blog.query.all()
    form = UpdateForm()
    return render_template('index.html',blogs = blogs,update_form = form)

@main.route('/contact',methods = ["GET","POST"])
@login_required
def mail():
    form = UpdateForm()
    if form.validate_on_submit():
        sub = Subscriber(email = form.email.data, username = form.username.data)
        db.session.add(sub)
        db.session.commit()

        mail_message("Thank you for subscibing to our email","email/welcome_user",sub.email,sub=sub)

        return redirect(url_for('main.index'))
    return render_template('contact.html',update_form = form)

@main.route('/new/blog', methods = ['GET','POST'])
@login_required
def new_blog():

    form = BlogForm()
    if form.validate_on_submit():
        blog = form.blog.data
        category = form.category.data
        title = form.title.data
        
        
        new_blog = Blog(blog = blog,title = title,category = category)
        new_blog.save_blog()
        
        user = current_user
        mail_message("New Post on the Blog","email/new_post",user.email,user=user,new_blog = new_blog)

        return redirect(url_for('main.index'))

    return render_template('new_blog.html',blog_form = form)

@main.route('/blogs')
def blogs():

    blogs = Blog.query.all()
    return render_template('blog.html',blogs = blogs)

@main.route('/blog/comments/<int:blogs_id>', methods = ['GET','POST'])
@login_required
def comment(blogs_id):
    form = CommentForm()
    blogs = Blog.query.get(blogs_id)
    all_comments = Comment.query.filter_by(blogs_id = blogs_id).all()
    if form.validate_on_submit():
        comment = form.comment.data
        blogs_id = blogs_id
        
        new_comment = Comment(comment = comment,blogs_id = blogs_id)
        
        new_comment.save_comment()

        

        return redirect(url_for('.comment',blogs_id = blogs_id))


    return render_template('comment.html',comment_form = form, blogs = blogs, all_comments = all_comments)

@main.route('/about_me')
def about():

    return render_template('about_me.html')

@main.route('/quotes')
def quotes():

    quotes = get_quotes()
    return render_template('quotes.html',quotes = quotes)

@main.route('/collection')
def collection():

    return render_template('collection.html')

@main.route('/blog/delete/<blogs_id>', methods=['GET', 'POST'])
@login_required
def delete_blog(blogs_id):
    blog = Blog.query.get_or_404(blogs_id)
    # if blog.user != current_user:
    #     abort(404)
    blog.delete()
    return redirect(url_for('main.blogs'))

@main.route('/comment/delete/<comments_id>', methods=['GET', 'POST'])
@login_required
def delete_comment(comments_id):
    comment = Comment.query.get_or_404(comments_id)
    # if blog.user != current_user:
    #     abort(404)
    comment.delete()
    return redirect(url_for('main.blogs'))

app/templates/base.html
{% extends 'bootstrap/base.html'%}

{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}


{% block footer %}
    {% include 'footer.html' %}
{% endblock footer %}

app/templates/blog.html
{% extends 'base.html'%}

{% block styles %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
    integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Quicksand&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@500&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Crimson+Text&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{{ url_for('static',filename='css/blog.css') }}">
{% endblock %}

{% block content %}

<div class="container-fluid">
    <h1
        style="text-align: center; margin-top: 70px; padding-bottom: 50px; font-family: 'DM Serif Display', serif; font-size: 60px;">
        BLOGS</h1>
    <div class="button">
        <a href="/new/blog"><button type="button" class="btn btn-dark btn2">ADD A NEW BLOG</button></a>
    </div>
</div>
<div class="container" style="margin-left: 250px; margin-bottom: 50px;">
    {% for blog in blogs [::-1] %}
    <div class="card" style="width: 50rem; font-family: 'Quicksand', sans-serif; border: none; border-bottom: solid rgba(182, 176, 176, 0.74) 1px;">
        <div class="card-body">
            <h5 class="card-title">{{ blog.title }}</h5>
            <h6 class="card-subtitle mb-2"></h6>
            <p class="card-text">{{ blog.blog }}</p>
            <a href="{{ url_for('main.comment',blogs_id = blog.id) }}"><button type="button" class="btn btn-outline-dark btn2">Comments</button></a>
            <a href="{{url_for('main.delete_blog',blogs_id = blog.id)}}"><button type="button" class="btn btn-outline-dark btn2">DELETE</button></a>
        </div>
    </div>
    {% endfor %}
</div>
<div class="container-fluid" style="height: 400px; border: none; border-top: solid rgba(182, 176, 176, 0.74) 1px;">
    <h2 style="font-family: 'Josefin Sans', sans-serif; padding-top: 20px;">Contact US</h2>
    <p style="font-family: 'Crimson Text', serif; font-size: 20px;">lewismaybach@gmail.com</p>
    <p style="font-family: 'Crimson Text', serif; font-size: 20px;">773-317-4433</p>
    <p style="font-family: 'Crimson Text', serif; font-size: 20px; padding-top: 20px;">4443  Oakmound Road</p>
    <p style="font-family: 'Crimson Text', serif; font-size: 20px;">Lombard</p>
    <p style="font-family: 'Crimson Text', serif; font-size: 20px;">Illinois</p>
    <p style="font-family: 'Crimson Text', serif; font-size: 20px;">2021 Awesome, Inc.</p>
</div>
<div class="ico">
    <a href="https://www.facebook.com/" style="color: inherit;" ><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-facebook"
        viewBox="0 0 16 16">
        <path
            d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z" />
    </svg></a>
    <a href="https://twitter.com/?lang=en" style="color: inherit;"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter"
        viewBox="0 0 16 16">
        <path
            d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z" />
    </svg></a>
    <a href="https://www.instagram.com/" style="color: inherit;"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-instagram"
        viewBox="0 0 16 16">
        <path
            d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z" />
    </svg></a>
    <a href="https://slack.com/" style="color: inherit;"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-slack"
        viewBox="0 0 16 16">
        <path
            d="M3.362 10.11c0 .926-.756 1.681-1.681 1.681S0 11.036 0 10.111C0 9.186.756 8.43 1.68 8.43h1.682v1.68zm.846 0c0-.924.756-1.68 1.681-1.68s1.681.756 1.681 1.68v4.21c0 .924-.756 1.68-1.68 1.68a1.685 1.685 0 0 1-1.682-1.68v-4.21zM5.89 3.362c-.926 0-1.682-.756-1.682-1.681S4.964 0 5.89 0s1.68.756 1.68 1.68v1.682H5.89zm0 .846c.924 0 1.68.756 1.68 1.681S6.814 7.57 5.89 7.57H1.68C.757 7.57 0 6.814 0 5.89c0-.926.756-1.682 1.68-1.682h4.21zm6.749 1.682c0-.926.755-1.682 1.68-1.682.925 0 1.681.756 1.681 1.681s-.756 1.681-1.68 1.681h-1.681V5.89zm-.848 0c0 .924-.755 1.68-1.68 1.68A1.685 1.685 0 0 1 8.43 5.89V1.68C8.43.757 9.186 0 10.11 0c.926 0 1.681.756 1.681 1.68v4.21zm-1.681 6.748c.926 0 1.682.756 1.682 1.681S11.036 16 10.11 16s-1.681-.756-1.681-1.68v-1.682h1.68zm0-.847c-.924 0-1.68-.755-1.68-1.68 0-.925.756-1.681 1.68-1.681h4.21c.924 0 1.68.756 1.68 1.68 0 .926-.756 1.681-1.68 1.681h-4.21z" />
    </svg></a>
    <a href="https://www.youtube.com/" style="color: inherit;"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-youtube"
        viewBox="0 0 16 16">
        <path
            d="M8.051 1.999h.089c.822.003 4.987.033 6.11.335a2.01 2.01 0 0 1 1.415 1.42c.101.38.172.883.22 1.402l.01.104.022.26.008.104c.065.914.073 1.77.074 1.957v.075c-.001.194-.01 1.108-.082 2.06l-.008.105-.009.104c-.05.572-.124 1.14-.235 1.558a2.007 2.007 0 0 1-1.415 1.42c-1.16.312-5.569.334-6.18.335h-.142c-.309 0-1.587-.006-2.927-.052l-.17-.006-.087-.004-.171-.007-.171-.007c-1.11-.049-2.167-.128-2.654-.26a2.007 2.007 0 0 1-1.415-1.419c-.111-.417-.185-.986-.235-1.558L.09 9.82l-.008-.104A31.4 31.4 0 0 1 0 7.68v-.122C.002 7.343.01 6.6.064 5.78l.007-.103.003-.052.008-.104.022-.26.01-.104c.048-.519.119-1.023.22-1.402a2.007 2.007 0 0 1 1.415-1.42c.487-.13 1.544-.21 2.654-.26l.17-.007.172-.006.086-.003.171-.007A99.788 99.788 0 0 1 7.858 2h.193zM6.4 5.209v4.818l4.157-2.408L6.4 5.209z" />
    </svg></a>
</div>
{% endblock %}